spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: http://localhost:8084
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1 # removes '/auth' from the forwarded request
            - RemoveRequestHeader=Origin   # <--- This removes the Origin header
        - id: app-service
          uri: http://localhost:8081
          predicates:
            - Path=/app/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Origin
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/noti/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Origin
        - id: notification-service-ws
          uri: ws://localhost:8082
          predicates:
            - Path=/ws/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Origin



logging:
  level:
    org:
      springframework:
        security: DEBUG
        cloud:
          gateway: DEBUG


server:
  port: 8083

jwt:
  secret: tonylimkeytonylimkeytonylimkeytonylimkeytonylimkey
  expiration_time: 1000000