spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: http://localhost:8084
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1 # removes '/auth' from the forwarded request
            - RemoveRequestHeader=Origin   # <--- This removes the Origin header
        - id: app-service
          uri: http://localhost:8081
          predicates:
            - Path=/app/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Origin
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/noti/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Origin
        - id: notification-service-ws
          uri: ws://localhost:8082
          predicates:
            - Path=/ws/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Origin



logging:
  level:
    org:
      springframework:
        security: DEBUG
        cloud:
          gateway: DEBUG


server:
  port: 8083

jwt:
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlnVIoAz6kmuPTseeUdTC
    YyyAYoap11UIHwb8IabmEmAXqAhBiHgEVDUYylfcrMnYnePCKgdJgJxafRrC0z03
    aTMbT6hG/f8JWg4ceOWND0S0jQvv6LYs2yAEiCe7jxTYB5Bdq54d/4AdE8hJU/K7
    G/RU4h7WgZRf5QQurNJJrkGWePIk4ojWMTl9leleVBn9ao6IMoawCT6yZtK0xJoc
    oeFj26PCpppTs23X4l+SLLmKO8yamReMITVFlVLeWPlgsLtnucl+JIYTQ8UPQ4au
    CgyhcybMXDoIFXAsGTQj9FvPEXYc8v38I7u86PAdAjKy8noJYG0X1xyr6tJweky2
    EwIDAQAB
    -----END PUBLIC KEY-----