spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: http://localhost:8084
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1 # removes '/auth' from the forwarded request
            - RemoveRequestHeader=Origin   # <--- This removes the Origin header

  data:
    redis:
      host: localhost
      port: 16379


logging:
  level:
    org:
      springframework:
        security: DEBUG
        cloud:
          gateway: DEBUG


server:
  port: 8083

jwt:
  secret: tonylimkeytonylimkeytonylimkeytonylimkeytonylimkey
  expiration_time: 999999999
